### ISSUE TITLE
could not read Username for 'https://github.com': No such device or address

### ISSUE THREAD

**Issue by Jarod1662** [GuillaumeFalourd/create-other-repo-branch-action#9]
Trying to test this action however when running the workflow, I get the following error message: 

![image](https://github.com/GuillaumeFalourd/create-other-repo-branch-action/assets/35074371/03c6aae9-2398-4eea-85ef-790162ec26e9)

I've tried different ways to get this to work such as specifying the git username and email. setting the GH_TOKEN at the global workflow level and running actions/checkout@v3 but no luck. any advice here?

**Comment by GuillaumeFalourd** [comment]
Hi @Jarod1662 , thank you for opening this issue!

Did you try using the action `access_token` input instead of setting the `GH_TOKEN` as env variable?

Something like this:
```
    steps:
      - uses: GuillaumeFalourd/create-other-repo-branch-action@v1.5
        with:
          repository_owner: <OWNER>
          repository_name: <REPO>
          new_branch_name: <BRANCH>
          new_branch_ref: <REF>
          access_token: ${{ secrets.GITHUB_TOKEN }}
          git_user_name: <USERNAME>
          git_user_email: <EMAIL>
```

Just to check, as the action could maybe use this value as default when not informed.
